version: '3.2'

services:
  resurface:
    image: resurfaceio/pilot:2.2.8
    container_name: spark_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  spark:
    image: test-spark
    container_name: test_spark_app
    ports:
      - '80:8080'
    env_file:
      - .env
